backend:
  name: github
  repo: tommaso-negri/volley-summer-camp

media_folder: static/assets
public_folder: assets

collections:
  - name: post
    label: Post
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: subtitle, label: Subtitle }
      - { name: round, label: Round, widget: select, options: ['1', '2'] }
      - { name: frontImg, label: Featured Image, widget: image }
      - { name: published, label: Published, widget: "boolean", default: true }
      - { name: body, label: Body, widget: markdown }